import type { Metadata } from "next";
import "../globals.css"
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Classdrift",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-secondary-white-400 font-jost">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
